### ISSUE TITLE
Rearrange Query page Options to the Top

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#11]
As Mr. Brooks recommended, it would be a better choice to move all the options and editable elements to the top of the query page, leaving the long body text field at the bottom. The submit button can also be moved to the top, allowing for a unified "control panel" that would not require the user scrolling around the page to edit LaTeX preferences.

**Comment by colorblast** [comment]
When are you going to do this?

**Comment by brian-i** [comment]
Today!

**Comment by brian-i** [comment]
Latest commit fixes this.
Sorry for the lateness. I was _really_ trying to set up my own server to prevent Issue #16, but failed miserably.
