### ISSUE TITLE
easyMark is Failing

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#12]
Numerous errors are arising from easyMark, including,
- Adding two backslashes "\" instead of one.
- Using strange hexadecimal encoding for `\begin{enumerate}`
- Not functioning with the find-and-replace notation that converts brackets to curly braces. ("Structuring Your Paper" section)

I spent a ridiculously long time trying to make it work to no avail.

**Comment by colorblast** [comment]
Does easyMark work now?

**Comment by brian-i** [comment]
The first two bullet points are theoretically fixed, but I am not sure about the third one.
