### ISSUE TITLE
Python recognizes \ as the special char the backspace

### ISSUE THREAD

**Issue by colorblast** [JonW27/labob#13]
\ will automatically be \e08 which will be the backspace character and wrecks up the LaTeX formatting as documented by this image.

![screen shot 2016-06-03 at 6 38 46 pm](https://cloud.githubusercontent.com/assets/8844453/15794644/6f2b7196-29ba-11e6-8eab-d9e606f990e3.jpg)

**Comment by brian-i** [comment]
To be specific, `\b` functions as the backspace character.
This isn't an issue, it's a feature!

**Comment by colorblast** [comment]
TESTED AND CONFIRMED. RAW STRINGS FIX IT.

**Comment by brian-i** [comment]
It should; thanks for testing.
I am working on the content return of the Python code, so may you not commit for now?

**Comment by colorblast** [comment]
I already commited. It now also solves the naming problem as its raw, so it stays as a page.
![screen shot 2016-06-03 at 9 50 25 pm](https://cloud.githubusercontent.com/assets/8844453/15796871/317d202c-29d5-11e6-8a2e-49c884ea447f.jpg)
They can now rename the file as they wish.

**Comment by colorblast** [comment]
Fixed with commits https://github.com/JonW27/labob/commit/693b450aa00d0c23e3c7c03751cb8c8d9aee4d34 and https://github.com/JonW27/labob/commit/e674132885a817c73259c493889c6c3c169ea072
Closing.
