### ISSUE TITLE
Suggestion regarding general format

### ISSUE THREAD

**Issue by colorblast** [JonW27/labob#15]
Unfortunately, athough we can now generate the code, we are still unable to save it without it not being recognized as python. I suggest we change the content type of the processor to HTML, include a JS script to autoredirect to the appropiate page, and we use file i/o to generate the tex file. This would be useful when we get to the pdf situation since it would allow us to view the pdf. It would allow option routing, as right now the only option available is the plain TeX code.

**Comment by brian-i** [comment]
Sorry for being so inactive while you were moving ahead, but I think that I finally solved the file naming issue! I was working with my own copy while you were submitting commits, so I will not commit my changes yet until I will understand what changes will be applied. My processor creates a new output LaTeX source file on the server itself (as originally intended), but this file is not temporary (as of now, maybe forever, as it will be replaced, but there are security issues with that). The output file is named `output.tex` and can be immediately downloaded and opened in a TeX interpreter. You can see it work at [my server](http://marge.stuy.edu/~brian.isakov/labob/). Note that the Issue #13 fixes have not been applied yet.

**Comment by colorblast** [comment]
If your thing is still a git repo, you can push as a git branch, and I can review and merge them.
