### ISSUE TITLE
marge.stuy.edu missing ALL formatting templates/packages.

### ISSUE THREAD

**Issue by colorblast** [JonW27/labob#16]
![screen shot 2016-06-04 at 2 09 22 pm](https://cloud.githubusercontent.com/assets/8844453/15801269/22f106b6-2a5e-11e6-8cee-9bdcbcf498e0.jpg)
As you can see, pdflatex does not have the package apa6 causing an internal server error

**Comment by brian-i** [comment]
The server-side pdflatex is missing _all_ of the templates that are required for specific formatting.
I will try to add them manually.

**Comment by brian-i** [comment]
Important:
Issue after issue, there are too many packages that marge is missing to work with the different formats.
Would it be feasible to ask Mr. Brooks to install (update, rather) a specific package that might as well fix all of this?

**Comment by colorblast** [comment]
You can try.

**Comment by colorblast** [comment]
PROPOSAL: Since its highly unlikely anything will be done, I propose that we create another variable similar to lbasic except its just standard packages for the pdf, so it won't run into an error and will still generate it.

**Comment by brian-i** [comment]
What do you mean?

**Comment by colorblast** [comment]
Create a var similar to lbasic, but only has the standard package so the pdf will be generated.

**Comment by brian-i** [comment]
So if the PDF option is requested, I can just override the format selector and force the use of Standard?

**Comment by colorblast** [comment]
Yes.

**Comment by JonW27** [comment]
On an unrelated note, should I download mactex, and if so which mirror?

**Comment by brian-i** [comment]
With commit 44cc0fa, a private server is now in place that handles the templates and formats well.
