### ISSUE TITLE
HTML page gets overwritten

### ISSUE THREAD

**Issue by colorblast** [JonW27/labob#18]
Need to create a python random path generator that first checks to see if there is already a file at that PATH, and if it there isn't will create a file there.

**Comment by colorblast** [comment]
Fixed with commit https://github.com/JonW27/labob/commit/849f9f91f59d31a48bb432967fb5ea026433b7c8

**Comment by brian-i** [comment]
Not working?
![screen shot 2016-06-04 at 22 31 58](https://cloud.githubusercontent.com/assets/19416612/15803292/3070f44a-2aa4-11e6-8a9e-f91d04c69459.png)

**Comment by brian-i** [comment]
Also, why is it a problem if the HTML page gets rewritten?
As it currently stands, the information transfer is not encrypted. It would increase privacy not to keep a permanent log of generated HTML pages, _especially_ as they are always generated.
Additionally, this will prevent the issue of there being an ever-increasing number of HTML pages without building another function to have the server delete them after some time.

**Comment by colorblast** [comment]
It works for mine after I added the pages dir and changed its permissions, although it is less secure. It would be more problematic if it is rewritten since there are many external dependencies, which means even if the page is saved, they would have to save the custom fonts, external js, etc, which is burdensome.
