### ISSUE TITLE
Conflicting Changes - What Now?

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#21]
I think that I got the PDF generator and re-director to work (PDFs are generated only if requested and are replaced, but the user can save them to their computer. I have not been thinking about creating a PDF "storage" as with web-pages, but that may work as well).
The problem is that there are **conflicting changes** and I am not sure whether I should commit or not.
You can check http://marge.stuy.edu/~brian.isakov/labob/ to see the PDF generation.

**Comment by colorblast** [comment]
How the heck did you fix this?

**Comment by brian-i** [comment]
`if fxn=="pdf":`
`subprocess.Popen("pdflatex output", shell=True)`
`print "Location: output.pdf\r\n"`

**Comment by JonW27** [comment]
Is output supposed to be a variable?

**Comment by colorblast** [comment]
What is output supposed to be?

**Comment by colorblast** [comment]
Post your code and I'll run diff utility to see the differences, change it to work, and commit it.

**Comment by colorblast** [comment]
Or you can run a git merge and then do the diff changing yourself.

**Comment by brian-i** [comment]
I just did that.

**Comment by brian-i** [comment]
I just did that.
Maybe ...

**Comment by brian-i** [comment]
Did I do something wrong?

**Comment by colorblast** [comment]
Uh... the pdf doesn't change...

**Comment by colorblast** [comment]
and uh... why the heck is there visual basic?

**Comment by brian-i** [comment]
The PDF changes only if the Standard format is selected. There are problems with other formats as I outlined in Issue #16. Visual basic, and a whole lot of TeX files, were an attempt by me to manually save packages for pdflatex to use, Issue #16 as well.

**Comment by colorblast** [comment]
It still doesn't change.

**Comment by brian-i** [comment]
Can you check my copy at http://marge.stuy.edu/~brian.isakov/labob/ ?
Perhaps this is a permissions issue, so you can run
`chmod 707 output.*`
`chmod 707 processor.py`

**Comment by colorblast** [comment]
Are you sure that its chmod 707 output? That goes for the HTML file.

**Comment by colorblast** [comment]
Never mind the permissions. It works.
