### ISSUE TITLE
APA Requires Special Enumeration Commands

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#3]
As documented in [this link](http://ctan.mackichan.com/macros/latex/contrib/apa6/apa6.pdf#page=5), APA requires _special_ commands in LaTeX for enumeration. `\begin{enumerate}` might not work if we will be using it as a shortcut for the simplified notation processor.

**Comment by colorblast** [comment]
Anyway to fix this? I don't know much regarding the citing and its a pretty large paper.

**Comment by brian-i** [comment]
> Anyway to fix this? I don't know much regarding the citing and its a pretty large paper.

There is a way to fix this, but I will try sticking to standard enumeration commands to see what will happen.

**Comment by brian-i** [comment]
With commit 36340b2 and the default-generated PDF file, it can be seen that the standard `\begin{enumerate}` syntax works as expected and can be used with APA formatting. As of now, I will close the issue because of the compatibility. However, there is a new `\begin{seriate}` command that is supported exclusively by APA. It may be better not to develop with it because of the incompatibility with other formats and the ability to re-create this enumeration command otherwise, without using APA.
