### ISSUE TITLE
APA Requires "Affiliation" Field

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#4]
New affiliation field (as in name of university or sponsor) needs to be added to query page.
This field should go under the author field.
APA default style requirement. :-/

**Comment by colorblast** [comment]
![screen shot 2016-05-30 at 6 10 46 pm](https://cloud.githubusercontent.com/assets/8844453/15659035/200b30e0-2692-11e6-886c-3f2a4d381914.jpg)

![screen shot 2016-05-30 at 6 13 51 pm](https://cloud.githubusercontent.com/assets/8844453/15659074/94afa8d6-2692-11e6-9c2f-96e60c4b7985.jpg)

**Comment by brian-i** [comment]
Thanks for the help.
