### ISSUE TITLE
Quotation marks Invalid

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#5]
The quotation marks in `qcorrecter()` are invalid, and they cannot be read with this encoding.

**Comment by colorblast** [comment]
I had this problem yesterday when I was building another project, the recommended way is to use the .encode method to allow reading.

**Comment by colorblast** [comment]
bug fixed with https://github.com/JonW27/labob/commit/1d4d3cd7588e8b0246117dba6fd153fa1f1773fa
