### ISSUE TITLE
Add font size to query page.

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#6]
Perhaps one of the greatest edits for text formatting is font size, which has been incorporated into the Python latex creator. Please add `fSize` into the query page. `fSize` can be any number + pt, as in `12pt`, or left blank for automatic formatting. Include a warning not to meddle with the font size to preserve document formatting authenticity and guidelines.
The CGI line added to Python is as follows:
`fontsize = userInput['fSize'].value`

**Comment by colorblast** [comment]
Do I need to include the +pt or will it auto be added in the processor code?

**Comment by brian-i** [comment]
> Do I need to include the +pt or will it auto be added in the processor code?

Add the pt as well please.
Never mind, I'll do that.

**Comment by colorblast** [comment]
Closed with commit https://github.com/JonW27/labob/commit/2d79ba46d4dbc9b99af13719a4c35ae768c1bc3e
