### ISSUE TITLE
Change abstract fields and integration on Query page.

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#7]
The "starter" field as appears on the query page is confusing and harder to implement in Python, especially when some document formats have specific abstract fields. APA has such a field. Please add an explicit `Abstract` field to the query page that will take in text from the user who knows that this text will only be used for APA. To make this clear to the user, please add a note that the abstract field is specifically and only for APA formatting.
The CGI line in Python has been added as follows:
`abstract = userInput['Abstract'].value`

**Comment by brian-i** [comment]
To be more specific, please see the [Jonathan: Abstract Changes.png](https://github.com/JonW27/labob/blob/master/Jonathan:%20Abstract%20Changes.png) file which shows a visual change.
The image is also visible below:
![jonathan_ abstract changes](https://cloud.githubusercontent.com/assets/19416612/16097111/01daf6c0-331a-11e6-9838-053b4886ae29.png)

**Comment by JonW27** [comment]
The file is corrupt.

**Comment by brian-i** [comment]
Did it, with your help, thanks!
