### ISSUE TITLE
Possible to Italicise text in a drop-down menu?

### ISSUE THREAD

**Issue by brian-i** [JonW27/labob#9]
The [photo from my latest commit](https://github.com/JonW27/labob/blob/master/Jonathan-%20Italicize%20Possible%3F.png) shows it all. I was unable to make the greyed-out "Note" text in the menu italicized.
The image has been removed from the above link and can be seen below:
<img width="863" alt="jonathan- italicize possible" src="https://cloud.githubusercontent.com/assets/19416612/16097146/385909a8-331a-11e6-80c6-08c6acd85b0a.png">

**Comment by colorblast** [comment]
Its not universally supported.

**Comment by colorblast** [comment]
the comment I made on your latest comment has a link that shows it all.
